=== Dudko-Mikhail/JavaWebDevelopment/XMLParsing/src/test/resources/data/banks.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/banks"
        xmlns:tns="http://www.example.com/banks"
        elementFormDefault="qualified">
    <element name="banks"> <!-- TODO add optional attribute (somewhere) -->
        <complexType>
            <sequence>
                <element name="bank" type="tns:Bank" maxOccurs="unbounded">
                    <key name="accountId">
                        <selector xpath="tns:depositors/tns:depositor/tns:deposits/tns:deposit"/>
                        <field xpath="@accountId"/>
                    </key>
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Bank">
        <sequence>
            <element name="name" type="tns:nonEmptyString"/>
            <element name="country" type="tns:nonEmptyString"/>
            <element name="depositors">
                <complexType>
                    <sequence>
                        <element name="depositor" type="tns:Depositor" maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
            </element>
        </sequence>
        <attribute name="bankId" type="ID" use="required"/>
    </complexType>

    <complexType name="Depositor">
        <sequence>
            <element name="deposits">
                <complexType>
                    <sequence>
                        <element name="deposit" type="tns:Deposit" maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
            </element>
        </sequence>
        <attribute name="name" use="required">
            <simpleType>
                <restriction base="tns:nonEmptyString">
                    <maxLength value="40"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="Deposit">
        <complexContent>
            <extension base="tns:MoneyStorage">
                <sequence>
                    <element name="profitability">
                        <simpleType>
                            <restriction base="tns:nonNegativeDecimal"/>
                        </simpleType>
                    </element>
                    <element name="depositTerm" type="date"/>
                    <element name="depositType">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="DEMAND_DEPOSIT"/>
                                <enumeration value="FIXED_TERM_DEPOSIT"/>
                                <enumeration value="SETTLEMENT_DEPOSIT"/>
                                <enumeration value="SAVINGS_DEPOSIT"/>
                                <enumeration value="ACCUMULATIVE_DEPOSIT"/>
                                <enumeration value="METALLIC_DEPOSIT"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
                <attribute name="accountId" use="required" type="long"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="MoneyStorage">
        <sequence>
            <element name="moneyAmount">
                <simpleType>
                    <restriction base="tns:nonNegativeDecimal">
                        <fractionDigits value="2"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
        <attribute name="currency" use="optional" default="USD">
            <simpleType>
                <restriction base="string">
                    <enumeration value="USD"/>
                    <enumeration value="EUR"/>
                    <enumeration value="BYN"/>
                    <enumeration value="RUB"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <simpleType name="nonNegativeDecimal">
        <restriction base="decimal">
            <pattern value="(0|([1-9]\d*))(\.\d+)?"/>
        </restriction>
    </simpleType>

    <simpleType name="nonEmptyString">
        <restriction base="string">
            <minLength value="1"/>
        </restriction>
    </simpleType>

</schema>

=== Dudko-Mikhail/JavaWebDevelopment/XMLParsing/src/test/resources/data/correctBanks.xml
<?xml version="1.0" encoding="UTF-8" ?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.example.com/banks"
       xsi:schemaLocation="http://www.example.com/banks banks.xsd">
    <bank bankId="b1">
        <name>BSB</name>
        <country>Belarus</country>
        <depositors>
            <depositor name="Misha">
                <deposits>
                    <deposit accountId="1">
                        <moneyAmount>34.21</moneyAmount>
                        <profitability>45</profitability>
                        <depositTerm>2021-10-14</depositTerm>
                        <depositType>SETTLEMENT_DEPOSIT</depositType>
                    </deposit>
                </deposits>
            </depositor>
        </depositors>
    </bank>
</banks>

=== Dudko-Mikhail/JavaWebDevelopment/XMLParsing/src/test/resources/data/IncorrectBanks.xml
<?xml version="1.0" encoding="UTF-8" ?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.example.com/banks"
       xsi:schemaLocation="http://www.example.com/banks banks.xsd">
    <bank bankId="b1">
        <name>VTB</name>
        <country>Belarus</country>
        <depositors>
            <depositor name="Misha">
                <deposits>
                    <deposit accountId="1">
                        <moneyAmount>34.21</moneyAmount>
                        <profitability>5</profitability>
                        <depositTerm>2021-10-14</depositTerm>
                        <depositType>SETTLEMENT_DEPOSIT</depositType>
                    </deposit>
                </deposits>
            </depositor>
        </depositors>
    </bank>
    <bank bankId="b1">
        <name>MTBank</name>
        <country>Belarus</country>
        <depositors>
            <depositor name="Gosha">
                <deposits>
                    <deposit accountId="1">
                        <moneyAmount>341</moneyAmount>
                        <profitability>10</profitability>
                        <depositTerm>2021-10-14</depositTerm>
                        <depositType>METALLIC_DEPOSIT</depositType>
                    </deposit>
                </deposits>
            </depositor>
        </depositors>
    </bank>
</banks>

=== Dudko-Mikhail/JavaWebDevelopment/XMLParsing/src/main/resources/data/banks.xml
<?xml version="1.0" encoding="UTF-8" ?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.example.com/banks"
       xsi:schemaLocation="http://www.example.com/banks banks.xsd">
    <bank bankId="b1">
        <name>BSB</name>
        <country>Belarus</country>
        <depositors>
            <depositor name="Misha">
                <deposits>
                    <deposit accountId="12">
                        <moneyAmount>500.45</moneyAmount>
                        <profitability>3</profitability>
                        <depositTerm>2020-12-02</depositTerm>
                        <depositType>SAVINGS_DEPOSIT</depositType>
                    </deposit>
                    <deposit accountId="1" currency="BYN">
                        <moneyAmount>800.17</moneyAmount>
                        <profitability>45.36</profitability>
                        <depositTerm>2020-12-18</depositTerm>
                        <depositType>ACCUMULATIVE_DEPOSIT</depositType>
                    </deposit>
                    <deposit accountId="7" currency="RUB">
                        <moneyAmount>4.63</moneyAmount>
                        <profitability>10</profitability>
                        <depositTerm>2014-03-08</depositTerm>
                        <depositType>DEMAND_DEPOSIT</depositType>
                    </deposit>
                </deposits>
            </depositor>
            <depositor name="Yaroslav">
                <deposits>
                    <deposit accountId="2">
                        <moneyAmount>1000</moneyAmount>
                        <profitability>12</profitability>
                        <depositTerm>2021-12-30</depositTerm>
                        <depositType>FIXED_TERM_DEPOSIT</depositType>
                    </deposit>
                </deposits>
            </depositor>
        </depositors>
    </bank>
    <bank bankId="b2">
        <name>VTB</name>
        <country>Belarus</country>
        <depositors>
            <depositor name="Gosha">
                <deposits>
                    <deposit accountId="12">
                        <moneyAmount>500.45</moneyAmount>
                        <profitability>3</profitability>
                        <depositTerm>2020-12-02</depositTerm>
                        <depositType>SAVINGS_DEPOSIT</depositType>
                    </deposit>
                    <deposit accountId="1" currency="BYN">
                        <moneyAmount>478</moneyAmount>
                        <profitability>14.36</profitability>
                        <depositTerm>2021-12-18</depositTerm>
                        <depositType>SETTLEMENT_DEPOSIT</depositType>
                    </deposit>
                    <deposit accountId="7" currency="RUB">
                        <moneyAmount>4.63</moneyAmount>
                        <profitability>454</profitability>
                        <depositTerm>2014-03-08</depositTerm>
                        <depositType>DEMAND_DEPOSIT</depositType>
                    </deposit>
                </deposits>
            </depositor>
            <depositor name="Kiril">
                <deposits>
                    <deposit accountId="4" currency="EUR">
                        <moneyAmount>900.45</moneyAmount>
                        <profitability>5</profitability>
                        <depositTerm>2022-10-30</depositTerm>
                        <depositType>SAVINGS_DEPOSIT</depositType>
                    </deposit>
                </deposits>
            </depositor>
        </depositors>
    </bank>
    <bank bankId="b3">
        <name>Belinvestbank</name>
        <country>Belarus</country>
        <depositors>
            <depositor name="Vlad">
                <deposits>
                    <deposit accountId="1">
                        <moneyAmount>280</moneyAmount>
                        <profitability>6</profitability>
                        <depositTerm>2022-10-07</depositTerm>
                        <depositType>SAVINGS_DEPOSIT</depositType>
                    </deposit>
                    <deposit accountId="2" currency="BYN">
                        <moneyAmount>399</moneyAmount>
                        <profitability>45.36</profitability>
                        <depositTerm>2020-12-18</depositTerm>
                        <depositType>ACCUMULATIVE_DEPOSIT</depositType>
                    </deposit>
                </deposits>
            </depositor>
            <depositor name="Ivan">
                <deposits>
                    <deposit accountId="3" currency="EUR">
                        <moneyAmount>4100</moneyAmount>
                        <profitability>2.05</profitability>
                        <depositTerm>2022-04-20</depositTerm>
                        <depositType>FIXED_TERM_DEPOSIT</depositType>
                    </deposit>
                </deposits>
            </depositor>
        </depositors>
    </bank>
</banks>

=== Dudko-Mikhail/JavaWebDevelopment/XMLParsing/src/main/resources/banks.xml
<?xml version="1.0" encoding="UTF-8" ?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.example.com/banks"
       xsi:schemaLocation="http://www.example.com/banks banks.xsd">
    <bank bankId="b1">
        <name>BSB</name>
        <country>Belarus</country>
        <depositors>
            <depositor name="Misha">
                <deposits>
                    <deposit accountId="12">
                        <moneyAmount>500.45</moneyAmount>
                        <profitability>3</profitability>
                        <depositTerm>2020-12-02</depositTerm>
                        <depositType>SAVINGS_DEPOSIT</depositType>
                    </deposit>
                    <deposit accountId="1" currency="BYN">
                        <moneyAmount>399</moneyAmount>
                        <profitability>45.36</profitability>
                        <depositTerm>2020-12-18</depositTerm>
                        <depositType>ACCUMULATIVE_DEPOSIT</depositType>
                    </deposit>
                    <deposit accountId="7" currency="RUB">
                        <moneyAmount>4.63</moneyAmount>
                        <profitability>454</profitability>
                        <depositTerm>2014-03-08</depositTerm>
                        <depositType>DEMAND_DEPOSIT</depositType>
                    </deposit>
                </deposits>
            </depositor>
        </depositors>
    </bank>
    <bank bankId="b41">
        <name>BSB</name>
        <country>Belarus</country>
        <depositors>
            <depositor name="Gosha">
                <deposits>
                    <deposit accountId="12">
                        <moneyAmount>500.45</moneyAmount>
                        <profitability>3</profitability>
                        <depositTerm>2020-12-02</depositTerm>
                        <depositType>SAVINGS_DEPOSIT</depositType>
                    </deposit>
                    <deposit accountId="1" currency="BYN">
                        <moneyAmount>399</moneyAmount>
                        <profitability>45.36</profitability>
                        <depositTerm>2020-12-18</depositTerm>
                        <depositType>ACCUMULATIVE_DEPOSIT</depositType>
                    </deposit>
                    <deposit accountId="7" currency="RUB">
                        <moneyAmount>4.63</moneyAmount>
                        <profitability>454</profitability>
                        <depositTerm>2014-03-08</depositTerm>
                        <depositType>DEMAND_DEPOSIT</depositType>
                    </deposit>
                </deposits>
            </depositor>
        </depositors>
    </bank>
</banks>
